### PR TITLE
PDCT-721/change_deleted_text_for_no_documents

### PR DESCRIPTION
**Pull request by asacristani**
Create an alias function to rename the status for "DELETED" families to "NO DOCUMENTS" instead.

Manually tested only

### CODE REVIEW

**Comment by asacristani** [comment]
image

**Comment by asacristani** [comment]
Please note that this only change the status in the Family List (no in other lists or detail view)

**Review by PatFawbertMills — APPROVED** [review]

**Comment by PatFawbertMills** [comment]
Good one 👍

**Review by diversemix — APPROVED** [review]
Nice - have an ice cream :ice_cream:

**Review by katybaulch — APPROVED** [review]
Looks great!! 🚗

**Pull request merged**
