### PR TITLE
ci: Reduce reviewers scope

### PR DESCRIPTION
**Pull request by jesse-c**
# What's changed

From a discussion in the product<>engineering retro today. The `tech-devs` team is quite broad, and ends up with people receiving a lot of emails.

## Proposed version

Please select the option below that is most relevant from the list below. This
will be used to generate the next tag version name during auto-tagging.

- [x] Skip auto-tagging
- [ ] Patch
- [ ] Minor version
- [ ] Major version

Visit the [Semver website](https://semver.org/#summary) to understand the
difference between `MAJOR`, `MINOR`, and `PATCH` versions.

Notes:

- If none of these options are selected, auto-tagging will fail
- Where multiple options are selected, the most senior option ticked will be
  used -- e.g. Major > Minor > Patch
- If you are selecting the version in the list above using the textbox, make
  sure your selected option is marked `[x]` with no spaces in between the
  brackets and the `x`

### CODE REVIEW

**Review by THOR300 — APPROVED** [review]
LGTM

**Review by katybaulch — CHANGES_REQUESTED** [review]
Hey Jesse, this is definitely the sort of thing we want to be doing! We had a conversation just before you joined about renaming our teams into platform and application. I'm not sure whether these new teams have been created in GitHub yet, but we want to change the team responsible in this PR from tech-dev to application rather than the old software team :slightly_smiling_face:

**Comment by olaughter** [comment]
Hey @katybaulch, they haven't been created yet. From what I remember there was some synchronisation needed on changing the names so we wouldn't break existing workflows. I'm not sure when we'll get time to switch, so would suggest this goes in now so we can start benefiting from it and we revisit when we get to it?

**Comment by olaughter** [comment]
I've just added the team to this repo so the codeowenrs file is now valid 😁

**Comment by jesse-c** [comment]
@katybaulch: That's good to know! And @olaughter I'm a fan of the progressive approach too, and thank you for adding the team 😉

**Review by katybaulch — APPROVED** [review]
lgtm - will need updating to `application` at some point but for now this is great for reducing reviewer scope :)

**Comment by jesse-c** [comment]
Thank you @katybaulch and @olaughter!

**Pull request merged**
